### ISSUE TITLE
Consider less restrictive licensing

### ISSUE THREAD

**Issue by matt0x6F** [alanorth/hugo-theme-bootstrap4-blog#103]
Hey Alan,

I really dig your work. It helped inspire me as I was learning Hugo. I have since ported my theme over and made a lot of changes. That said, GPL-3 is quite a restrictive license and basically forces me to continue licensing GPL-3 and will not allow me to upgrade to a "more free" license such as MIT. As this doesn't really appear to be a commercial product, I was hoping to be able to relicense my distribution as MIT and give you a clear mention.

What are your thoughts?

**Comment by matt0x6F** [comment]
Also, for the sake of transparency:

[A preview of the repo](https://github.com/mattouille/bootstrap4)

[My original site](https://github.com/mattouille/mattouille.github.io)

**Comment by alanorth** [comment]
You're welcome for the theme, and thanks for the thoughtful comment. Your blog looks great! I like how you updated the look to be more modern.

The "freedom" of the GPL vs MIT license is an endless debate, but I did choose GPL purposefully because its goal is to protect users and to keep contributions open. The GPL does not forbid commercial activity. Its main assertion is that if you distribute copies of the software—for free or for a fee—you must also include the source code.

Having said that, I'm actually not sure that I'm _allowed_ to license this theme as GPL. This theme is based on the example "blog" theme as it appeared for several versions up to and including Bootstrap v4 Alpha 6, and their [docs and examples are licensed CC-BY-3.0](https://v4-alpha.getbootstrap.com/examples/). I'm not sure if that means I need to re-license this as CC-BY-3.0? Also, then, theoretically I should probably get approval from all people who contributed code to it (unless I was never allowed to re-license it anyways, in which case it was always CC-BY-3.0). Hmm...

**Comment by matt0x6F** [comment]
Yeah, that's a really good question - mine is the same. If you look at my Jekyll site (original) the theme itself was from BlackRockDigital at StartBootstrap. I just wrote all the logic.

I want to say contributors can independently license _their_ work when forking a project? I'm not a lawyer and honestly, it's kind of confusing. The good thing about both of these licenses is it seems we're able to do whatever we see as the "right" thing until someone points out it _should_ be different.

Both of the pages I used are MIT licensed:
* https://startbootstrap.com/template-overviews/blog-home/
* https://startbootstrap.com/template-overviews/blog-post/

I didn't actually retain much (if any) of your design, so maybe that mitigates the CC-BY-3.0 concerns. I did keep your language files and some of the logic in place though, which I think you deserve credit for.

Would you object to me giving you proper credit for the boilerplate and a link to your project?

(I did also use your selective SASS implementation, which was brilliant - I don't use SASS much so I didn't know you could do that). Also, I used your JSON-LD over my implmentation. 

I could go on - there's a significant amount of non-theme code that you wrote that I think is more what I'm interested in upgrading the license for.

**Comment by alanorth** [comment]
> (I did also use your selective SASS implementation, which was brilliant - I don't use SASS much so I didn't know you could do that). Also, I used your JSON-LD over my implmentation.

The SASS thing really helps reduce the size of Bootstrap, and the JSON-LD thing is honestly one of the reasons I haven't moved to another theme all this time. I was really proud of that, and nobody seems to pay such close attention to the metadata in my opinion (though luckily I contributed to Hugo's built-in template too, so it's better now there too).

I'd be happy if you used my code and simply acknowledged its origins. Regarding the licensing, to be honest, I should probably change the license to CC-BY-3.0 so it matches the one used in Bootstrap's documentation, as I don't think it was within my rights to "change" it to GPL in the first place.

I am not a lawyer either, and if this was a large project re-licensing without getting permission from all previous contributors would probably be front-page news on Hacker News and Slashdot.

**Comment by matt0x6F** [comment]
Haha yeah, I got into that discussion earlier. The good thing is drawing a seperation between _your_ code and _template_ code, which maybe I should do on my project. I don't know quite how I'll do this, but I'll work on it and drop an update here.

If I use acknowledgments in the file is there a website/email/etc you want me to drop in?

**Comment by alanorth** [comment]
License changed to CC-BY-3.0 in d26cb4cf557d936430d7ce8585754ea4ad2ba30f. Thanks for the discussion, @mattouille.
