### ISSUE TITLE
prefetch of web fonts

### ISSUE THREAD

**Issue by fte378** [alanorth/hugo-theme-bootstrap4-blog#11]
Hi Alan,

on GTmetrix.com I saw that loading the webfont (font-awesome) delays displaying the page significantly (shown there in the waterfall view). It was loaded after the css file was interpreted and took some time of course.

I tried to include the following in the head section of my page:

<link rel="prefetch" href="/fonts/fontawesome-webfont.woff" />
<link rel="prefetch" href="/fonts/fontawesome-webfont.woff2" />

Of course this leaves out the other font encodings but I think including them all is overkill.

The result showed no change for the Firefox rendering engine but the Chrome engine (desktop and mobile) started to download the font in parallel to the images. So the load time was reduced. For slow connections the result may be different.
It also introduced a warning about "doubled" content:  the woff file once without parameter and once with the version number appended as parameter.

What do you think about font-preloading? Do you have experiences regarding this?

Regards, Frank

**Comment by alanorth** [comment]
I haven't used these myself, but I'm familiar with them. Here's a good article about some of the options available: [Prefetching, preloading, prebrowsing](https://css-tricks.com/prefetching-preloading-prebrowsing/). It seems `prefetch` is probably worth it for Font Awesome, since we're _definitely_ going to load those resources anyways.

For my Hugo blog I am not using Google Analytics or Disqus, so there are no external sites/resources I need to connect to, but if your user's browser is going to connect to those servers for resources, it might be good to `dns-prefetch` or `preconnect` to those domains, as I see [my WordPress blog does](https://englishbulgaria.net).

The good news is that the site itself is pretty small. I find that for [my site](https://picturingjordan.com/) the largest things are the images, so I limit the front page to only display the latest three posts using the `paginate` parameter.

**Comment by alanorth** [comment]
Ok, I read more on this. I'm not going to do any prefetching or preloading of Font Awesome at this time. There are a lot of tradeoffs to consider here, including:
- [`prefetch` isn't recommended](https://helloanselm.com/2015/using-webfonts-in-2015/), [`preload` isn't widely supported yet](http://caniuse.com/#feat=link-rel-preload), and both of them have [misleading names](https://twitter.com/AndyDavies/status/652042630487015424) as well
- We have several versions of Font Awesome, and definitely don't want to load more than one on any browser. We can't know which one the browser supports (WOFF2, WOFF, EOT, etc) until they load the style sheet, so it's better to let the browser choose. See [this issue](https://github.com/w3c/preload/issues/28) on the w3c issue tracker

Font Awesome is only used for icons, so it's not as important as when you use "normal" web fonts for your page's text (see flash of unstyled text, flash of invisible text, etc). To that effect, Bootstrap v4 uses the system's native fonts for body text, so we're actually already very light!
