### ISSUE TITLE
Generating localized dates in template

### ISSUE THREAD

**Issue by prkpv** [alanorth/hugo-theme-bootstrap4-blog#38]
As I understand it there in Hugo localization date, but there is a workaround.
https://discuss.gohugo.io/t/generating-localized-dates-in-template/2393/4
Just do not understand how to apply it in the template.

**Comment by alanorth** [comment]
Hmm, the [workaround basically relies on localizing the month strings](https://github.com/nicolinuxfr/voiretmanger-hugo/commit/5ecc162a0e89d803997fff5e9ef0a2507c0ff6d0) and printing them. There are two problems: first, it means we need the month names in all other languages, and second, that the date format itself is no longer configurable via `params.date_format`.

Closing this for now because it's too hacky. Let's cross our fingers and hope that the Golang templating functions can't do this natively right now.
