### ISSUE TITLE
Disable sharing for a single item

### ISSUE THREAD

**Issue by fte378** [alanorth/hugo-theme-bootstrap4-blog#46]
Hi,

I have two pages which are "public" in a sense but are excluded by robots.txt.
I would like to be able to turn the sharing icons off for these too - the same way as
the comments can be turned off (sharing = false).

Regards, Frank

**Comment by alanorth** [comment]
Yes, I could see how someone might want to turn off sharing icons on a page/post basis. I will have to think about how to do this, trying to keep all of the possible combinations of variables and simplicity in mind!

**Comment by alanorth** [comment]
Ok, I think I can make the logic in `layouts/_default/single.html` more simple if I make the sharing icons a simple on/off thing, rather than allowing for hiding certain icons (because this is another variable scope and had to be tested in an annoying way).

How do you feel about a simple config / frontmatter option like this?

```
sharingicons = false
```

It would default on (to show icons), unless turned off in the site config or frontmatter.

**Comment by alanorth** [comment]
Ok, I decided to implement this as above. Now it works like this: sharing icons are enabled by default, but you can set `sharingicons = false` in the site's config or in individual page/post frontmatter to toggle the setting there. Thanks for the idea, and the opportunity to simplify the template logic a bit.

See: https://github.com/alanorth/hugo-theme-bootstrap4-blog/commit/2459ad9567e834c2370f3f8bae88b3dea97bf610

**Comment by fte378** [comment]
Great! Many thanks for the fast implementation!

Regards, Frank
