### ISSUE TITLE
blockquotes aren't distinguished at all

### ISSUE THREAD

**Issue by xenoterracide** [alanorth/hugo-theme-bootstrap4-blog#50]
This [post](https://blog.xenoterracide.com/post/solving-code-generation-problems-in-dzil/) has a number of blockquotes, none of which have different formatting and so you can't tell what's being quoted. screenshot contains quoted and unquoted text.

![image](https://cloud.githubusercontent.com/assets/5517/23979780/9e3e0256-09c9-11e7-9500-e991c3ef9769.png)

![image](https://cloud.githubusercontent.com/assets/5517/23979805/ce4025e2-09c9-11e7-9446-ae160b5d8c76.png)

**Comment by alanorth** [comment]
Ah, yes, this is unfortunate. [Bootstrap's blockquote syntax](https://v4-alpha.getbootstrap.com/content/typography/#blockquotes) requires class `blockquote` in order to apply styling, see this example:

![screen shot 2017-03-16 at 11 50 53-fs8](https://cloud.githubusercontent.com/assets/191754/23990518/01e33efa-0a3f-11e7-95f9-1f697115c4f3.png)

So the HTML code that Hugo generates for Markdown-style blockquotes doesn't get style applied when using Bootstrap's default config.

**Comment by alanorth** [comment]
Thanks @xenoterracide. Fixed in https://github.com/alanorth/hugo-theme-bootstrap4-blog/commit/132d659955a1fbbda88c29df7b58f0035f5cfe8b by applying Bootstrap's same style to all `<blockquote>` tags.

**Comment by xenoterracide** [comment]
Thanks :D I might consider filing a bug with bootstrap too.. because I notice this is a change from 3.x, and I'm not sure that it needs to be.
