### ISSUE TITLE
Make it work with Hugo's quick-start

### ISSUE THREAD

**Issue by cemsbr** [alanorth/hugo-theme-bootstrap4-blog#89]
`hugo new posts/my-first-post.md` from [Hugo docs](https://gohugo.io/getting-started/quick-start/#step-4-add-some-content) is not working, but `hugo new post/my-first-post.md`. According to Hugo's maintainer in gohugoio/hugoDocs/pull/395, this should be fixed in this template.

**Comment by alanorth** [comment]
Seems like a logical change that will "just work" for lots of people. I hadn't noticed the introduction of the quasi magical `.Site.Params.mainSections` because Hugo releases so often and it's easy to miss stuff.

Anyways, I can fix the front page and sidebar recent post lists to use `.Site.Params.mainSections`, but the top navigation menu will be trickier. When I created this theme I lazily relied on populating that menu with everything that _wasn't a post_ — this will break that. I would have to think of another way to populate the menu, perhaps via frontmatter or site configuration like the current `[[menu.sidebar]]`.

**Comment by fte378** [comment]
In any case [[menu.sidebar]]  and [[menu.navbar]] should still work.

**Comment by alanorth** [comment]
@fte378 I forgot that there was already machinery for `[[menu.navbar]]`! Great, so I can just remove the `custom_navbar` thing and then make the top bar explicitly use `[[menu.navbar]]` if it is set (either in the site config or content front matter).

I will fix the code and update the README.md and exampleConfig to use this.
